services:

  postgres:
    image: postgres:17
    container_name: todo-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/db/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7
    container_name: todo-redis

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  migrate:
    build:
      context: ./backend

    entrypoint: ["uv", "run", "python", "-m", "app.db.migrate"]
    command: ["run"]

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

    depends_on:
      postgres:
        condition: service_healthy

    restart: "no"


  backend:
    build:
      context: ./backend

    container_name: todo-backend

    ports:
    - "8000:8000"
    
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_TTL_SECONDS: ${CACHE_TTL_SECONDS:-60}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: HS256
      JWT_EXPIRE_MINUTES: 60
      OSS_ACCESS_KEY_ID: ${OSS_ACCESS_KEY_ID}
      OSS_ACCESS_KEY_SECRET: ${OSS_ACCESS_KEY_SECRET}
      OSS_REGION: ${OSS_REGION}
      OSS_BUCKET: ${OSS_BUCKET}
      OSS_ENDPOINT: ${OSS_ENDPOINT}
      OSS_DOMAIN: ${OSS_DOMAIN}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully


  frontend:
    build:
      context: ./frontend

    container_name: todo-frontend

    ports:
      - "8080:80"

    depends_on:
      - backend


volumes:
  postgres_data:
